### PR TITLE
Add Keybase widget showing grincoin#general chat

### PR DESCRIPTION
**Pull request by nijynot**
This PR adds a Keybase chat widget showing the grincoin#general channel.

As Keybase does not have an open API to access team messages, this solution relies on me serving team message and member count from these two endpoints:
- `https://grin.nijynot.com/messages` and
- `https://grin.nijynot.com/team`.

I did not go with Chia's `keybase-live-feed` at the end as I feel it was a bit too complicated for a small chat widget, and it'd be faster to just build it from scratch (given that we'd want to change the UI). `grin-keybase-chat` is instead a Node.js server on a Digital Ocean droplet and the repo can be found on [mimblewimble/keybase-chat-widget](https://github.com/mimblewimble/keybase-chat-widget).

### CODE REVIEW

**Comment by lehnberg** [comment]
Very cool @nijynot, well done as always!! 😀

Don't really have much to add aside from some nit-pick, here goes:
 
* If you like, I'm happy to create a repo for the widget under /mimblewimble, might give it a bit more exposure and attention from other contributors. If you prefer to have it under you that's absolutely fine.
* The project is generally `Apache-2.0` but I notice the widget is `MIT`. Would you consider changing?
* And kind of a side point to this PR, I have a nagging suspicion that with all the myriad keybase teams and channels we use, we suffer a major discoverability problem. It would be nice to have more of these widgets showing (for example for #dev, and for node and wallet teams), but not sure whether it's an overkill, and/or how we would structure it on the website? Do you have some thoughts about this?

once again, awesome work! 👏

**Comment by nijynot** [comment]
Good points!

1. I think it makes sense to makes sense to move the repo to mimblewimble. It’s made for the grin.mw site afterall.
1. Yes can switch to Apache-2.0, no prob!
1. Good idea. Thinking about adding a dropdown that lets you switch channels, between wallet general and community general and whatnot. What do you think?

**Comment by lehnberg** [comment]
Awesome! Will just check with others that there are no new-repo-objections 👍  

> Thinking about adding a dropdown that lets you switch channels, between wallet general and community general and whatnot. What do you think?

Oh, that would be super! :D

**Comment by lehnberg** [comment]
@nijynot repo created here, https://github.com/mimblewimble/keybase-chat-widget
I also added you to the site-dev team giving you commit rights to both `/site` and this repo. :)

Perhaps it makes sense to update this pr so that it points to the new repo before we merge?

**Comment by nijynot** [comment]
Migrated over to the new repo and updated the link to point to it too.

**Comment by lehnberg** [comment]
Awesome! However, Github fired a security vulnerability alert in the repo based on `serialize-javascript < 2.1.1` as defined in `yarn.lock`:
 
```
Remediation

Upgrade serialize-javascript to version 2.1.1 or later. For example:

serialize-javascript@^2.1.1:
  version "2.1.1"
```

Any chance we can fix this on your deployment before we merge it?

**Comment by lehnberg** [comment]
> Awesome! However, Github fired a security vulnerability alert in the repo based on `serialize-javascript < 2.1.1` as defined in `yarn.lock`:
> 
> ```
> Remediation
> 
> Upgrade serialize-javascript to version 2.1.1 or later. For example:
> 
> serialize-javascript@^2.1.1:
>   version "2.1.1"
> ```
> 
> Any chance we can fix this on your deployment before we merge it?

Actually this shouldn't be a blocker I realise, sorry about that. It's not related to /site but to your deployment in the end and I will open an issue I the repo instead. LGTM :+1:

**Pull request merged**
