### PR TITLE
Add Documentation Link

### PR DESCRIPTION
**Pull request by quentinlesceller**
Replace GitHub link by "Documentation" link in top bar.

### CODE REVIEW

**Review by Paouky — APPROVED** [review]

**Comment by antiochp** [comment]
Do we still have a reasonably prominent link somewhere to github?

**Comment by quentinlesceller** [comment]
We still have it at the bottom of the page.
Capture d’écran 2020-09-29 à 13 48 18

**Comment by Paouky** [comment]
Considering the core team is likely about to become a council managing the fund, maybe we can keep the GitHub link and instead remove the Governance tab?

**Comment by kargakis** [comment]
There is also a link in the [Get Started page](https://github.com/mimblewimble/site/blob/5a3fd94d8151ebe38d9184ff92ca5cce31c906b2/get-started.html#L19) that should change to point at the new docs site.

**Comment by kargakis** [comment]
Actually there is [another one in the Get Started page](https://github.com/mimblewimble/site/blob/5a3fd94d8151ebe38d9184ff92ca5cce31c906b2/get-started.html#L45) that can change to https://docs.grin.mw/wiki/services/list-of-services/.

**Comment by Paouky** [comment]
@kargakis I have a [PR](https://github.com/mimblewimble/site/pull/223) going to modify the Get Started page.

**Comment by lehnberg** [comment]
Could we find a way to make room for both Docs and Github in the top menu? Arguably two of the most crucial links for us to have.

**Comment by quentinlesceller** [comment]
Updated to keep both links. Please review @Paouky @lehnberg @kargakis @antiochp thanks!
Preview:
Capture d’écran 2020-09-30 à 12 24 47

**Review by Paouky — APPROVED** [review]
Looks good to me. though I do think we eventually want to minimize the number of tabs up there.

**Review by kargakis — APPROVED** [review]
Agreed with @Paouky about minimizing the tabs in the future. Maybe Governance can be collapsed into Community.

**Review by lehnberg — APPROVED** [review]

**Comment by lehnberg** [comment]
Okay, merging for now, we can iterate on the top bar later, related: https://github.com/mimblewimble/site/issues/172

**Pull request merged**
