### PR TITLE
add alternative twitter account

### PR DESCRIPTION
**Pull request by Paouky**
current twitter account is banned, would be beneficial to have an alternative one available for those interested

### CODE REVIEW

**Comment by quentinlesceller** [comment]
Can you send a screen cap?

**Comment by Paouky** [comment]
> Can you send a screen cap?


image

**Comment by Paouky** [comment]
Maybe this would be better, what do you think? 

image

**Comment by quentinlesceller** [comment]
At this point I think we can remove the previous twitter account too. Also wondering since your Twitter account is not "official" (whatever that means ) if we should simply keep only the other channels. Any opinion on this @lehnberg ?

**Comment by lehnberg** [comment]
Agree, it might be better to remove twitter altogether.

**Comment by Paouky** [comment]
https://github.com/mimblewimble/site/pull/215

**Pull request closed without merging**
