### PR TITLE
Add Nervos to leaderboard and Friends of Grin

### PR DESCRIPTION
**Pull request by lehnberg**
## Description
- Adds Nervos to entities
- Adds Nervos logos
- Adds Nervos to friends of Grin

Related: https://github.com/mimblewimble/grin-pm/pull/326

## Screenshots
Leaderboard
Friends

### CODE REVIEW

**Comment by Paouky** [comment]
Is it necessary to mention "The only"? Seems a bit like pure marketing talk. I think it's enough to describe what it actually is, without this prompt.

**Comment by lehnberg** [comment]
@paouky these are not my words, but the ones Nervos wanted to have included as part of their leaderboard entry, something every position in the top 10 is entitled to have.

**Comment by j01tz** [comment]
Haven't tested the SVGs but content looks ok. Is the friends of grin logo supposed to be rendered as it is in the screenshot with the name overlay on the logo?

**Comment by lehnberg** [comment]
> Is the friends of grin logo supposed to be rendered as it is in the screenshot with the name overlay on the logo?

That's just my mouse hovering over the image as I took the screenshot, showing the alt text of the image.

**Comment by lehnberg** [comment]
Merging this. If something doesn't look good we can improve further in another PR.

**Pull request merged**
