### PR TITLE
update fund amount (+10)

### PR DESCRIPTION
**Pull request by Paouky**
Update the size of the fund following the 10BTC [Nervos donation](https://forum.grin.mw/t/a-message-from-nervos/7568/7).

### CODE REVIEW

**Comment by quentinlesceller** [comment]
Actually this amount is not regularly updated but right now it's 108.09025836 BTC https://blockstream.info/address/bc1qecw954uappnwhle6tmafqskn6vxmpr6lmmuwfwldphfxplcshgnssy9kmx

**Comment by Paouky** [comment]
> Actually this amount is not regularly updated but right now it's 108.09025836 BTC https://blockstream.info/address/bc1qecw954uappnwhle6tmafqskn6vxmpr6lmmuwfwldphfxplcshgnssy9kmx

Alright. 
And while I'm at it, is the grin balance displayed somewhere so it can be updated without calculating from the txs log?

**Comment by quentinlesceller** [comment]
No unfortunately the grin node is maintained by @yeastplume and I don't think there is a way to do it automatically. Maybe some wizardry is possible.

**Comment by lehnberg** [comment]
Thanks for the PR @Paouky. 

I've opted to only update the balance once per quarter based on the financial transparency reports (which is why they are linked, as proofs). Prior to this, we were updating on an ad-hoc basis which was error prone and inefficient to manage correctly. 

I have an action to produce a new report and update it for Q2. The Nervos donation would appear in Q3. 

Keeping the amount automatically up to date is something we've yet to support, but is interesting to explore.

**Comment by Paouky** [comment]
@lehnberg Got it. I'm producing useless PRs but at least I'm learning!

**Comment by lehnberg** [comment]
No worries! We've all been there 👍

**Pull request closed without merging**
