### PR TITLE
add SparkPool into Grin Friends page

### PR DESCRIPTION
**Pull request by garyyu**
Tx Id: https://etherscan.io/tx/0x34460d9d8c9610109fe16f88939e03e8b2982613dcb95fa0459b995e75df5499

To: Yeastplume Funding Campaign
From: [SparkPool](https://www.sparkpool.com)
Amount: 100 ETH

Notes from SparkPool founder:
> More will come
>
> And constantly

### CODE REVIEW

**Comment by ignopeverell** [comment]
Thank you very much!

**Comment by garyyu** [comment]
Updated to keep a record here for Sparkpool's 2nd donation:
Tx Id: https://www.blockchain.com/zh/btc/tx/147b921ac69042cd1bac5ca0b2715b8a2951f0bd9f27232260ed0a7a6d0563b0

To: Yeastplume Funding Campaign
From: SparkPool
Amount: 2.38217288 BTC

**Comment by garyyu** [comment]
Updated to keep a record here for Sparkpool's 3rd donation on 2019.03.03:

To: Grin General Fund
Amount: 5500 GRIN (on the current price $3.68 USD / Grin, it's 20,240 USD).

ignotus 
4:39 AM I can confirm a 5500 grins donation on our wallet

**Comment by lehnberg** [comment]
@garyyu just to make you aware that we now have this: https://github.com/mimblewimble/grin-pm/blob/master/financials/income_log.csv -> Would be awesome if you could help me keep track of these donations in there. :)

**Comment by garyyu** [comment]
@lehnberg Cool! 
and can we move `grin-pm/financials/income_log.csv` into `site` repo?  then we can avoid using two PR to modify both repo.

**Comment by lehnberg** [comment]
I think the governance meeting decided it should be in `grin-pm`, which also makes sense to me intuitively. I believe it  should be straight forward to point any logic on `site` to look into `grin-pm` for this.

**Comment by garyyu** [comment]
> I think the governance meeting decided it should be in grin-pm.

At that time, we didn't know we will have `Hall of Fame` and didn't know we will have `History` feature on `Hall of Fame`. So we'd better to discuss again and change it, to use same repo.

> which also makes sense to me intuitively

I'm afraid now it's not so intuitively :-)  when a donation is done, we need a PR to modify the site to add the Friends page, and we need another PR to modify `grin-pm/financials/income_log.csv`.

So, I still think moving it into site repo is the best choice.

**Pull request merged**
