### PR TITLE
 add FB page url in footer & navigation.html

### PR DESCRIPTION
**Pull request by MegaSolar**
I add Grin/MW facebook PR page url in footer.html & navigation.html in `_include`.

Please check & confirm. :) 

any feedbacks would be welcomed.

### CODE REVIEW

**Comment by MegaSolar** [comment]
@lehnberg ping. :)

**Comment by lehnberg** [comment]
Thanks for the PR @MegaSolar. 

We discussed how to promote various grin communities on the webpage [in a governance meeting in January](https://github.com/mimblewimble/grin-pm/blob/master/notes/20190117-meeting-governance.md#82-chat-channels-and-communities), and opted to only promote Gitter on the website and then link to the [wiki page](https://github.com/mimblewimble/docs/wiki/News-and-Channels#communities) where other communities are listed. I notice you have added the facebook page there already, nice!

Based on that decision, I don't think we should add a link to this facebook page on the website directly.

**Comment by MegaSolar** [comment]
@lehnberg Thanks for your guidance. 
I understand governance decision & admit it. 

then I close this PR.

**Comment by MegaSolar** [comment]
@lehnberg Following `23th Apr governance meeting`, I think community members consider evangelism. 
So [grin's FB page](https://www.facebook.com/GRIN.MimbleWimble)  subscribers more than 30,000 ppl. 

Grin community can use this resource.

**Comment by kargakis** [comment]
@MegaSolar seems you already added the FB page in https://github.com/mimblewimble/docs/wiki/News-and-Channels#communities which is great. 

The grin evangelism point is a bit different from the promotion of the channels. We want **people** to evangelize Grin, FB is a **channel** that these people can use. I hope you see the difference now and the point is clearer.

**Comment by MegaSolar** [comment]
@kargakis thanks for your explanation.
From grin main-net started, I, myself promoted grin on my own budget and its subscribers the largest in the FB. you can search it.

I suggest that even development side is important that I agree but public adoption also necessary either. 
so I can give this  **channel**'s operation authority who is involving in grin project contributor. 
Please consider that. 

thanks.

**Pull request closed without merging**
