### PR TITLE
Update site according to RFC0016 "simplify governance"

### PR DESCRIPTION
**Pull request by lehnberg**
Related discussion: https://forum.grin.mw/t/implementing-simplify-governance/7897

### This pull request:
* ~Specifies Rust implementation on front page~
* Removes the Governance section
* Updates the funding page with info about council and fund spending guidelines
* Moves RFC paragraph into Community page

### Live preview:
https://lehnberg.net/site/ (front page out of date, scroll down in this PR)

### CODE REVIEW

**Comment by Paouky** [comment]
```Specifies Rust implementation on front page```
I don't really like this. `@MW/Grin - The original Rust implementation.` is definitely not the first thing you'd want a new user to read. There are better ways to make the changes of simplify-governance more visibly prominent (as done here and the other ideas discussed in the forum thread).

Big thumbs up on the rest of the changes.

**Comment by lehnberg** [comment]
> There are better ways to make the changes of simplify-governance more visibly prominent

Can you specify some of those better ways @Paouky? 

Just saying you dislike something without offering any improvement suggestion is not helpful.

**Comment by Paouky** [comment]
> > There are better ways to make the changes of simplify-governance more visibly prominent
> 
> Can you specify some of those better ways @Paouky?
> 
> Just saying you dislike something without offering any improvement suggestion is not helpful.

But this is precisely the improvement suggestion; to simply remove it. Having this little clarification is not worth cluttering the landing page, which is supposed to be on the "marketing" side of things.

The other ways, as I mentioned, are the changes in your PR, and the other suggestion I raised in the thread which is to modifications to Download page (making grin++ more prominent as a full and valid implementation of Grin).

**Comment by lehnberg** [comment]
@Paouky part of the action from the RFC is to make it clear that the website is about the Rust project specifically and not "wider Grin".

Why should we not make that clear on the front page?

**Comment by johndavies24** [comment]
I agree with @Paouky and he disagreed with the solution as well, just leave it off and don't clutter the landing page. I think the landing page should be as clean as possible. I also think it's fine for different grin ecosystem websites to focus on themselves, but it's important for them to cross reference and highlight each other (when and where appropriate)

**Comment by lehnberg** [comment]
screenshot

@Paouky for the sake of moving forward, I've removed the sentence from the front page (see picture above), are you ok with this being merged?

cc @quentinlesceller - please take a look as well

**Comment by tromp** [comment]
It's an improvement. There's still some redundancy between the first and last sentences.

**Comment by antiochp** [comment]
> ```
> Specifies Rust implementation on front page
> ```
> 
> I don't really like this. `@MW/Grin - The original Rust implementation.` is definitely not the first thing you'd want a new user to read. There are better ways to make the changes of simplify-governance more visibly prominent (as done here and the other ideas discussed in the forum thread).
> 
> Big thumbs up on the rest of the changes.

Just to chime in with a suggestion - 
Can we call it the "reference implementation" instead of the "Rust implementation"?

**Comment by antiochp** [comment]
> > ```
> > Specifies Rust implementation on front page
> > ```
> > 
> > 
> > I don't really like this. `@MW/Grin - The original Rust implementation.` is definitely not the first thing you'd want a new user to read. There are better ways to make the changes of simplify-governance more visibly prominent (as done here and the other ideas discussed in the forum thread).
> > Big thumbs up on the rest of the changes.
> 
> Just to chime in with a suggestion -
> Can we call it the "reference implementation" instead of the "Rust implementation"?

Let's leave it off for now. Get this merged. And then we can revisit adding "reference impl" in a separate PR.

**Review by antiochp — APPROVED** [review]
:+1:

**Comment by Paouky** [comment]
For reference, I do think @antiochp 's suggestion to word it "Reference implementation" is pretty good. Perhaps we should add it to the bottom of the page. Should I make a PR?

**Pull request merged**
