### PR TITLE
Updated download.html

### PR DESCRIPTION
**Pull request by transatoshi-mw**
Updated to grin-wallet 5.3.1 and grin 5.3.2. Removed Niffler and Ironbelly and added Grim.

### CODE REVIEW

**Comment by transatoshi-mw** [comment]
I also removed info about homebrew and snap installs as I don't believe they are still maintained

**Review by Anynomouss — COMMENTED** [review]
Checked the changes and tested the hashes, looks good in general. 
I am not sure if it is already time to remove/out-comment Grin++ and Iron-belly or just tag them as not being actively maintained.

In any case it would make sense to add Grim wallet to the list and give it higher position in the list than Grin++ and Ironbelly since it is actively maintained and has no issues.

**Comment by yeastplume** [comment]
Sorry, just looking at site updates now after someone pointed out that changes need to be merged. I just merged the ironbelly removal at author's request in #269, and I'm about to undertake a retag and build of grin and grin wallet. Can we wait until all of these are done and then update the download page with very latest releases, remove niffler and add and Grim?

**Comment by cekickafa** [comment]
-Afaik Niffler works Rust node, you can add external nodes also it works atm. If GUI wallet releases, it can be replaced. 
-Grin++ banning/blacklisting peers. Not updated for a long time.
-Grim can be added instead of ironbelly imo.

**Comment by transatoshi-mw** [comment]
> Sorry, just looking at site updates now after someone pointed out that changes need to be merged. I just merged the ironbelly removal at author's request in #269, and I'm about to undertake a retag and build of grin and grin wallet. Can we wait until all of these are done and then update the download page with very latest releases, remove niffler and add and Grim?

Sounds good to me, I'll touch base with you in a bit when the new versions are ready I'll update the downloads page then.

**Comment by transatoshi-mw** [comment]
> -Afaik Niffler works Rust node, you can add external nodes also it works atm. If GUI wallet releases, it can be replaced. -Grin++ banning/blacklisting peers. Not updated for a long time. -Grim can be added instead of ironbelly imo.

I removed Niffler since I've only seen it mentioned when folks have downloaded it and had problems. I admittedly haven't been around long so I'm not familiar with it's status beyond seeing a few posts for help with running it and those people being recommended a different solution.

**Pull request closed without merging**
